---
# Pod definition
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: first-container
    image: anko47/test-jupyter:buildx-latest
    ports:
      - containerPort: 80

# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: first-container
        image: anko47/test-jupyter:buildx-latest
        # Add other container configuration as needed

# Service definition
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer

# Job definition
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      name: my-job
    spec:
      containers:
      - name: first-container
        image: anko47/test-jupyter:buildx-latest
        # Add other container configuration as needed
      restartPolicy: Never


