---
apiVersion: v1
kind: Pod
metadata:
  name: load-fastapi-naive
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - 'locust -f /app/load-testing/locustfile.py --host=http://app-fastapi.default.svc.cluster.local:8080 --users 2 --spawn-rate 5 --autostart --run-time 60s'
      image: anko47/app-fastapi:latest
      imagePullPolicy: Always
      name: load
      ports:
        - containerPort: 8089
          protocol: TCP
---