---
# Pod definition
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: first-container
    image: anko47/test-jupyter:buildx-latest
    ports:
      - containerPort: 80

# Job definition
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      name: my-job
    spec:
      containers:
      - name: jupyter-container
        image: anko47/test-jupyter:buildx-latest
      - name: app-ml-container
        image: anko47/app-ml:buildx-latest
        # Add other container configuration as needed
      restartPolicy: Never


