name: ci

on:
  pull_request:
    branches:
      - "main"

jobs:
  build-jupyter-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: install buildx
          id: buildx
          uses: crazy-max/ghaction-docker-buildx@v1
          with:
            version: latest

      -   name: build the image
          run: |
            docker buildx build \
              --tag ${{ secrets.DOCKERHUB_USERNAME }}/test-jupyter:buildx-latest \
              --platform linux/amd64,linux/arm64 ./jupyter-app
      -   name: push the image
          run: |
            docker buildx push ${{ secrets.DOCKERHUB_USERNAME }}/test-jupyter:buildx-latest ./jupyter-app

  buildx-app-ml:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./ml-app
          file: ./ml-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-ml:buildx-latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-ml:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-ml:buildcache,mode=max
            
