name: ci

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: install buildx
          id: buildx
          uses: crazy-max/ghaction-docker-buildx@v1
          with:
            version: latest

      -   name: build the image
          run: |
            docker buildx build \
              --tag ${{ secrets.DOCKERHUB_USERNAME }}/test-jupyter:buildx-latest \
              --platform linux/amd64,linux/arm64 ./jupyter-app
            
