name: serving-ci

on:
  push:
    branches:
      - 'Serving_1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build app streamlit
        uses: docker/build-push-action@v2
        with:
          context: Serving/
          file: Serving/Dockerfile
          push: true
          target: app-streamlit
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-streamlit:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-streamlit:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-streamlit:buildcache,mode=max

      - name: Build app fastapi
        uses: docker/build-push-action@v2
        with:
          context: Serving/
          file: Serving/Dockerfile
          push: true
          target: app-fastapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-fastapi:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-fastapi:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-fastapi:buildcache,mode=max
      - name: Test FastAPI server
        run: |
          export WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}
          docker run ${{ secrets.DOCKERHUB_USERNAME }}/app-fastapi:latest pytest -ss ./tests

