name: week-5-ci

on:
  push:
    branches:
      - 'Serving_1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build app streamlit
        uses: docker/build-push-action@v2
        with:
          context: week-5/
          file: week-5/Dockerfile
          push: true
          target: app-streamlit
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app-streamlit:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-streamlit:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-streamlit:buildcache,mode=max