name: general-tests

on:
  push:
    branches:
      - tests_cont
env:
  IMAGE_MAIN_NAME: classification-mnist
  IMAGE_MAIN_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build new
        run: |
          docker build -f classification/Dockerfile -t classification-mnist:latest classification

      - name: Load Data
        run: |
          docker run classification-mnist:latest make load_data

      - name: Test code
        run: |
          docker run classification-mnist:latest make test_code

      - name: Test data
        run: |
          docker run classification-mnist:latest make test_data

      - name: Test model
        run: |
          docker run classification-mnist:latest make test_model

      - name: Test all
        run: |
          docker run classification-mnist:latest make test_all

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: classification
          file: classification/Dockerfile_mac
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_MAIN_NAME }}:${{ env.IMAGE_MAIN_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_MAIN_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_MAIN_NAME }}:buildcache,mode=max
